### ISSUE TITLE
Padding prop not having an impact on the W10 NavPaneItem

### ISSUE THREAD

**Issue by spmcbride1201** [gabrielbull/react-desktop#78]
When working with NavPane and NavPaneItems, I noticed that the icons were offset from the hamburger button by quite a bit. In DevTools, it appears that the parent <span> for the NavPaneItem had padding of 16px on the left and the right. 

In the documentation, I noticed that the padding prop, I was unable to use this to reduce the padding issue above.

My current hack to get things to line up involves tagging your render function for the windows 10 NavPaneItem with a className and adding the following css.

```css
/* Hack to fix weird nav-icon alignment */
/* Tacked on className on /keypunch-electron/node_modules/react-desktop/src/navPane/windows/pane/item/item.js*/
span.navItem {
  padding-left: 5px !important;
}
```
This results in my icons lining up
![image](https://cloud.githubusercontent.com/assets/8700322/21630543/346c1904-d200-11e6-8b89-61cb6d000701.png)
